Action "index", controller "Index", module "VideoManager".

<div class="row">
    <table class="table table-bordered">
        <?php
            $output = array(
                'allRouteParams', 'paramPage',
                'allPostData', 'allGetData',
                'allHeaderData', 'allCookieData'
            );
        ?>
        <?php foreach ($output as $item): ?>
        <tr>
            <th><?php print $item; ?></th>
            <td><pre><?php print_r($this->$item); ?></pre></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>

<?php print $this->render('copyright'); ?>